### PR TITLE
prometheus-snmp-exporter: added configurationPath option

### PR DESCRIPTION
**Pull request by oida**
###### Motivation for this change

Prometheus snmp exporter ships a default config file (snmp.yml) within its repository, which can now be specified by the "configurationPath" option to be used instead of the "configuration" option, so it is not needed to convert the whole file into a nix attribute set anymore.
###### Things done
- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
  - [x] NixOS
  - [ ] OS X
  - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by globin** [comment]
Hi! I'm a bot that helps with reviewing and testing Nix code.

Commands:
- `@nixbot build` creates a new Hydra jobset and reports results

**Comment by groxxda** [comment]
@nixbox build

**Comment by groxxda** [comment]
Vielleicht die gegenseitige Exklusivität noch mit einer assertion absichern:
`assert (configurationFile == null) != (configuration == null);`

**Comment by fpletz** [comment]
@nixbot build

**Comment by globin** [comment]
Jobset created at XXXurl

Edit @fpletz: https://hydra.mayflower.de/jobset/hydra-pr-jobs/pr-14

**Comment by groxxda** [comment]
Natürlich müssen die Beschreibungstexte dann noch angepasst werden.

Übrigens:
`mkConfigFile = pkgs.writeText "snmp.yml" (if cfg.configurationFile == null then builtins.toJSON cfg.configuration else builtins.readFile cfg.configurationFile);` ist zwar ein geläufiges Idiom, aber meiner Meinung nach wäre schöner den Typ von configurationFile auf path zu ändern und dann `mkConfigFile = if (configuration != null) then pkgs.writeText "bla" builtins.toJSON configuration else configFile;` zu verwenden.. Allerdings ungetestet.

**Comment by globin** [comment]
Hi! I'm a bot that helps with reviewing and testing Nix code.

Commands:
- `@nixbot build` creates a new Hydra jobset and reports results

**Comment by globin** [comment]
Hi! I'm a bot that helps with reviewing and testing Nix code.

Commands:
- `@nixbot build` creates a new Hydra jobset and reports results

**Pull request merged**
