### PR TITLE
ympd: update source revision

### PR DESCRIPTION
**Pull request by WilliButz**
###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by Ma27** [comment]
the standard format for derivation names in NixOS that are created by a git revision/tag is `yyyy-mm-dd`. Do we want to change this here as well to keep it consistent to the official `nixpkgs` repo? (in this case we could use commit messages like `ympd: olddate -> newdate`)

**Comment by WilliButz** [comment]
@Ma27 You're right. I'm changing this for consistency ( even though this won't be cherry-picked back to master ^^).

**Comment by fpletz** [comment]
This ympd is only used in our fork. We don't use nix-env so the version is not really needed. :)

**Comment by Ma27** [comment]
ok, thanks for the clarification :)

**Pull request merged**
